databases:
  - name: whisper-db
    plan: free

services:
  - type: web
    name: whisper-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.13
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: whisper-db
          property: connectionString
