# Generated by Django 4.2.29 on 2026-03-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('property_type', models.CharField(max_length=100)),
                ('beds', models.PositiveSmallIntegerField()),
                ('baths', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price_min', models.PositiveIntegerField()),
                ('price_max', models.PositiveIntegerField()),
                ('stage', models.CharField(choices=[('premarket', 'Premarket'), ('private', 'Private')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.agentuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
