"""
Django settings for whisper project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

try:
    import dj_database_url
except ImportError:  # pragma: no cover - local fallback until deployment deps are installed
    dj_database_url = None

try:
    import whitenoise  # noqa: F401
except ImportError:  # pragma: no cover - local fallback until deployment deps are installed
    whitenoise = None

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-whisper-dev-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", False)
if not DEBUG and SECRET_KEY == "django-insecure-whisper-dev-key":
    raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG is false.")

ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",") if host.strip()]
DEV_EXPOSE_SIGNUP_LINKS = env_bool("DEV_EXPOSE_SIGNUP_LINKS", False)
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
WHISPER_TERMS_VERSION = os.getenv("WHISPER_TERMS_VERSION", "2026-03-v1")
WHISPER_PRIVACY_VERSION = os.getenv("WHISPER_PRIVACY_VERSION", "2026-03-v1")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'listings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]

if whitenoise is not None:
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')

MIDDLEWARE += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'listings.middleware.LegalAcceptanceMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'whisper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'whisper.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
if DATABASE_URL:
    if dj_database_url is None:
        raise ImproperlyConfigured("dj-database-url must be installed to use DATABASE_URL.")
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

RUNNING_TESTS = "test" in sys.argv

if whitenoise is not None:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": (
                "django.contrib.staticfiles.storage.StaticFilesStorage"
                if DEBUG or RUNNING_TESTS
                else "whitenoise.storage.CompressedManifestStaticFilesStorage"
            ),
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PRODUCT_NAME = os.getenv('PRODUCT_NAME', 'Whisper')
EMAIL_PROVIDER = os.getenv('EMAIL_PROVIDER')
DEFAULT_FROM_EMAIL = os.getenv('EMAILIT_FROM', 'hello@whispered.homes')
EMAILIT_API_URL = os.getenv('EMAILIT_API_URL', 'https://api.emailit.com/v2/emails')
EMAILIT_API_KEY = os.getenv('EMAILIT_API_KEY', '')
SITE_BASE_URL = os.getenv('SITE_BASE_URL') or (
    f'https://{RENDER_EXTERNAL_HOSTNAME}' if RENDER_EXTERNAL_HOSTNAME else 'http://localhost:8000'
)
LISTING_CHECKIN_LINK_MAX_AGE = 60 * 60 * 24 * 90
ACCOUNT_EMAIL_VERIFICATION_LINK_MAX_AGE = 60 * 60 * 24 * 7
ACCESS_REQUEST_SIGNUP_LINK_MAX_AGE = 60 * 60 * 24 * 7
AUTH_ACCESS_TOKEN_MAX_AGE = int(os.getenv("AUTH_ACCESS_TOKEN_MAX_AGE", str(60 * 30)))
QR_AUTH_ACCESS_TOKEN_MAX_AGE = int(os.getenv("QR_AUTH_ACCESS_TOKEN_MAX_AGE", str(60 * 10)))

# Retention policy: V1 only auto-cleans low-risk transient records.
AUTH_TOKEN_RETENTION_DAYS = int(os.getenv("AUTH_TOKEN_RETENTION_DAYS", "14"))
QR_AUTH_TOKEN_EXPIRED_RETENTION_DAYS = int(os.getenv("QR_AUTH_TOKEN_EXPIRED_RETENTION_DAYS", "1"))
QR_AUTH_TOKEN_USED_RETENTION_DAYS = int(os.getenv("QR_AUTH_TOKEN_USED_RETENTION_DAYS", "7"))
ACCESS_REQUEST_RETENTION_DAYS = int(os.getenv("ACCESS_REQUEST_RETENTION_DAYS", "90"))
REJECTED_ACCESS_REQUEST_RETENTION_DAYS = int(os.getenv("REJECTED_ACCESS_REQUEST_RETENTION_DAYS", "90"))
ENABLE_SESSION_RETENTION_CLEANUP = env_bool("ENABLE_SESSION_RETENTION_CLEANUP", True)
COLLECTION_ALERT_FALLBACK_LOOKBACK_DAYS = int(os.getenv("COLLECTION_ALERT_FALLBACK_LOOKBACK_DAYS", "7"))
LISTING_FRESHNESS_OPTIONAL_UPDATE_DAYS = 14
LISTING_FRESHNESS_REQUIRED_UPDATE_DAYS = 21
LISTING_FRESHNESS_REQUIRED_UPDATE_GRACE_DAYS = 3


NY_OPEN_DATA_BASE_URL = os.getenv("NY_OPEN_DATA_BASE_URL")
NY_REAL_ESTATE_DATASET_ID = os.getenv("NY_REAL_ESTATE_DATASET_ID")
NY_LICENSE_API_APP_TOKEN = os.getenv("NY_LICENSE_API_APP_TOKEN")
NY_LICENSE_API_TIMEOUT = int(os.getenv("NY_LICENSE_API_TIMEOUT", "10"))


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "listings": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
